<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'eventsourcing\\billingaddress' => '/domain/BillingAddress.php',
                'eventsourcing\\billingaddresssetevent' => '/domain/BillingAddressSetEvent.php',
                'eventsourcing\\cartitem' => '/domain/CartItem.php',
                'eventsourcing\\cartitemcollection' => '/domain/CartItemCollection.php',
                'eventsourcing\\cartnotfoundexception' => '/domain/CartNotFoundException.php',
                'eventsourcing\\cartservice' => '/CartService.php',
                'eventsourcing\\checkout' => '/Checkout.php',
                'eventsourcing\\checkoutservice' => '/CheckoutService.php',
                'eventsourcing\\checkoutstartedevent' => '/domain/CheckoutStartedEvent.php',
                'eventsourcing\\confirmpageprojector' => '/ConfirmPageProjector.php',
                'eventsourcing\\confirmpagerenderer' => '/ConfirmPageRenderer.php',
                'eventsourcing\\emitterid' => '/domain/EmitterId.php',
                'eventsourcing\\event' => '/domain/Event.php',
                'eventsourcing\\eventdispatcher' => '/EventDispatcher.php',
                'eventsourcing\\eventlistener' => '/EventListener.php',
                'eventsourcing\\eventlog' => '/domain/EventLog.php',
                'eventsourcing\\eventlogreader' => '/EventLogReader.php',
                'eventsourcing\\eventlogwriter' => '/EventLogWriter.php',
                'eventsourcing\\eventsourced' => '/domain/EventSourced.php',
                'eventsourcing\\factory' => '/Factory.php',
                'eventsourcing\\filesystemeventlogreader' => '/FileSystemEventLogReader.php',
                'eventsourcing\\filesystemeventlogwriter' => '/FileSystemEventLogWriter.php',
                'eventsourcing\\sessionid' => '/domain/SessionId.php',
                'eventsourcing\\sessionservice' => '/SessionService.php',
                'eventsourcing\\sessionupdater' => '/SessionUpdater.php',
                'eventsourcing\\snapshotevent' => '/domain/SnapshotEvent.php',
                'eventsourcing\\snapshotter' => '/Snapshotter.php',
                'eventsourcing\\timedfilesystemeventlogreader' => '/TimedFileSystemEventLogReader.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
